### ISSUE TITLE
Occasionally insistent film recommendation 

### ISSUE THREAD

**Issue by lascellesabercrombie** [alternadiva/HTTP-project#13]
For reasons I've not yet worked out, the app will sometimes keep on suggesting the same film and ignoring new country requests.

**Comment by sonianb** [comment]
That's probably because we haven't cleared the previous result? I'll have a look.

**Comment by lascellesabercrombie** [comment]
I think that's right! I've written some code that I think fixes it, though bigger problem of language code conversion remains!

**Comment by lascellesabercrombie** [comment]
Will push that in a moment, along with a better version of the adult film filter
